(macher-agent-make-tool macher-agent-delegate-tasks-to-subagents-tool
    "Delegate tasks to multiple sub-agents asynchronously."
  :category "orchestrate"
  :args (list '(:name "tasks" :type array :items (:type object :properties (:buffer_name (:type string) :instructions (:type string) :presets (:type array :items (:type string))))))
  :command-fn (lambda (payload)
                (let* ((raw-tasks (plist-get payload :tasks))
                       (normalized-tasks
                        (cl-loop for task-obj in (append raw-tasks nil)
                                 collect (let* ((raw-presets (or (plist-get task-obj :presets)
                                                                 (alist-get 'presets task-obj)
                                                                 (alist-get "presets" task-obj nil nil #'equal)))
                                                (preset-list (cond ((vectorp raw-presets) (append raw-presets nil))
                                                                   ((stringp raw-presets) (list raw-presets))
                                                                   ((listp raw-presets) raw-presets)
                                                                   (t nil))))
                                           (list :buffer_name (or (plist-get task-obj :buffer_name)
                                                                  (alist-get 'buffer_name task-obj)
                                                                  (alist-get "buffer_name" task-obj nil nil #'equal))
                                                 :instructions (or (plist-get task-obj :instructions)
                                                                   (alist-get 'instructions task-obj)
                                                                   (alist-get "instructions" task-obj nil nil #'equal))
                                                 :presets preset-list)))))
                  (make-macher-agent-delegate-response :payload (vconcat normalized-tasks))))
  :success-fn (lambda (results)
                (let ((output (list "All sub-agents completed. Outputs:\n")))
                  (cl-loop for res across (if (vectorp results) results (vconcat results))
                           do (push (format "=== Response from %s ===\n%s\n" 
                                            (macher-agent-tool-response-buffer-name res)
                                            (if (eq (macher-agent-tool-response-status res) 'success)
                                                (macher-agent-tool-response-data res)
                                              (macher-agent-tool-response-error res)))
                                    output))
                  (string-join (nreverse output) "\n"))))
